In [8]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:

# NumPy Operations
import numpy as np # Added import statement here


# 1. Creating Arrays
print(" NumPy: Creating Arrays")
array_1d = np.array([1, 2, 3, 4, 5])  # 1D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
ones = np.ones((3, 3))  # 3x3 matrix of ones

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)
print("Zeros Array:\n", zeros)
print("Ones Array:\n", ones)

# 2. Mathematical Operations
print("\nNumPy: Mathematical Operations")
array = np.array([1, 2, 3, 4])
print("Original Array:", array)
print("Array + 5:", array + 5)
print("Array * 2:", array * 2)
print("Array squared:", array ** 2)

# 3. Aggregate Functions
print("\nNumPy: Aggregate Functions")
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Standard Deviation:", np.std(array))

# 4. Reshaping and Transposing
print("\nNumPy: Reshaping and Transposing")
reshaped = array_2d.reshape((3, 2))
print("Reshaped Array:\n", reshaped)
print("Transposed Array:\n", array_2d.T)

# 5. Random Numbers
print("\n NumPy: Random Numbers")
random_array = np.random.rand(3, 3)  # Random values in [0, 1]
print("Random Array:\n", random_array)



 NumPy: Creating Arrays
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

NumPy: Mathematical Operations
Original Array: [1 2 3 4]
Array + 5: [6 7 8 9]
Array * 2: [2 4 6 8]
Array squared: [ 1  4  9 16]

NumPy: Aggregate Functions
Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895

NumPy: Reshaping and Transposing
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]

 NumPy: Random Numbers
Random Array:
 [[0.07036447 0.00528057 0.8355577 ]
 [0.64112218 0.29797842 0.81274815]
 [0.03947501 0.17054866 0.3596676 ]]


In [10]:
#Pandas Operations


# 1. Creating a DataFrame
print("\nPandas: Creating a DataFrame")
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 29],
    'Score': [85, 90, np.nan, 88]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# 2. Handling Missing Data
print("\n Pandas: Handling Missing Data")
print("Original DataFrame:\n", df)
df['Score'].fillna(df['Score'].mean(), inplace=True)  # Fill missing values with mean
print("After Filling Missing Data:\n", df)

# 3. Filtering Rows
print("\nPandas: Filtering Rows")
filtered_df = df[df['Age'] > 25]  # Filter rows where Age > 25
print("Filtered DataFrame:\n", filtered_df)

# 4. Grouping and Aggregation
print("\n Pandas: Grouping and Aggregation")
grouped_df = df.groupby('Age')['Score'].mean()  # Group by Age and calculate mean Score
print("Grouped DataFrame:\n", grouped_df)

# 5. Sorting Data
print("\nPandas: Sorting Data")
sorted_df = df.sort_values(by='Score', ascending=False)
print("Sorted DataFrame:\n", sorted_df)

# 6. Reading and Writing CSV
print("\nPandas: Reading and Writing CSV")
df.to_csv('output.csv', index=False)  # Save to CSV
loaded_df = pd.read_csv('output.csv')  # Read from CSV
print("Loaded DataFrame:\n", loaded_df)







Pandas: Creating a DataFrame
DataFrame:
       Name  Age  Score
0    Alice   24   85.0
1      Bob   27   90.0
2  Charlie   22    NaN
3    David   29   88.0

 Pandas: Handling Missing Data
Original DataFrame:
       Name  Age  Score
0    Alice   24   85.0
1      Bob   27   90.0
2  Charlie   22    NaN
3    David   29   88.0
After Filling Missing Data:
       Name  Age      Score
0    Alice   24  85.000000
1      Bob   27  90.000000
2  Charlie   22  87.666667
3    David   29  88.000000

Pandas: Filtering Rows
Filtered DataFrame:
     Name  Age  Score
1    Bob   27   90.0
3  David   29   88.0

 Pandas: Grouping and Aggregation
Grouped DataFrame:
 Age
22    87.666667
24    85.000000
27    90.000000
29    88.000000
Name: Score, dtype: float64

Pandas: Sorting Data
Sorted DataFrame:
       Name  Age      Score
1      Bob   27  90.000000
3    David   29  88.000000
2  Charlie   22  87.666667
0    Alice   24  85.000000

Pandas: Reading and Writing CSV
Loaded DataFrame:
       Name  Age      Sco

<ipython-input-10-2961caf18104>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(df['Score'].mean(), inplace=True)  # Fill missing values with mean
